// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GreenAPISendResponse green API send response
//
// swagger:model GreenAPISendResponse
type GreenAPISendResponse struct {

	// id message
	// Required: true
	IDMessage *string `json:"idMessage"`
}

// Validate validates this green API send response
func (m *GreenAPISendResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIDMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GreenAPISendResponse) validateIDMessage(formats strfmt.Registry) error {

	if err := validate.Required("idMessage", "body", m.IDMessage); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this green API send response based on context it is used
func (m *GreenAPISendResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GreenAPISendResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GreenAPISendResponse) UnmarshalBinary(b []byte) error {
	var res GreenAPISendResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
