// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GreenAPISendFileByURLRequest green API send file by URL request
//
// swagger:model GreenAPISendFileByURLRequest
type GreenAPISendFileByURLRequest struct {

	// api token instance
	// Required: true
	// Min Length: 1
	APITokenInstance *string `json:"apiTokenInstance"`

	// caption
	// Max Length: 1024
	Caption string `json:"caption,omitempty"`

	// chat Id
	// Required: true
	// Min Length: 1
	ChatID *string `json:"chatId"`

	// Имя файла с расширением
	// Required: true
	// Min Length: 1
	FileName *string `json:"fileName"`

	// id instance
	// Required: true
	// Min Length: 1
	IDInstance *string `json:"idInstance"`

	// quoted message Id
	QuotedMessageID string `json:"quotedMessageId,omitempty"`

	// URL файла, должен начинаться с http:// или https://
	// Required: true
	// Min Length: 1
	URLFile *string `json:"urlFile"`
}

// Validate validates this green API send file by URL request
func (m *GreenAPISendFileByURLRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPITokenInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCaption(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChatID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFileName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURLFile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GreenAPISendFileByURLRequest) validateAPITokenInstance(formats strfmt.Registry) error {

	if err := validate.Required("apiTokenInstance", "body", m.APITokenInstance); err != nil {
		return err
	}

	if err := validate.MinLength("apiTokenInstance", "body", *m.APITokenInstance, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendFileByURLRequest) validateCaption(formats strfmt.Registry) error {
	if swag.IsZero(m.Caption) { // not required
		return nil
	}

	if err := validate.MaxLength("caption", "body", m.Caption, 1024); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendFileByURLRequest) validateChatID(formats strfmt.Registry) error {

	if err := validate.Required("chatId", "body", m.ChatID); err != nil {
		return err
	}

	if err := validate.MinLength("chatId", "body", *m.ChatID, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendFileByURLRequest) validateFileName(formats strfmt.Registry) error {

	if err := validate.Required("fileName", "body", m.FileName); err != nil {
		return err
	}

	if err := validate.MinLength("fileName", "body", *m.FileName, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendFileByURLRequest) validateIDInstance(formats strfmt.Registry) error {

	if err := validate.Required("idInstance", "body", m.IDInstance); err != nil {
		return err
	}

	if err := validate.MinLength("idInstance", "body", *m.IDInstance, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendFileByURLRequest) validateURLFile(formats strfmt.Registry) error {

	if err := validate.Required("urlFile", "body", m.URLFile); err != nil {
		return err
	}

	if err := validate.MinLength("urlFile", "body", *m.URLFile, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this green API send file by URL request based on context it is used
func (m *GreenAPISendFileByURLRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GreenAPISendFileByURLRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GreenAPISendFileByURLRequest) UnmarshalBinary(b []byte) error {
	var res GreenAPISendFileByURLRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
