// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GreenAPISendMessageRequest green API send message request
//
// swagger:model GreenAPISendMessageRequest
type GreenAPISendMessageRequest struct {

	// api token instance
	// Required: true
	// Min Length: 1
	APITokenInstance *string `json:"apiTokenInstance"`

	// Формат: 79876543210@c.us (личный) или 120363043968066561@g.us (группа)
	// Required: true
	// Min Length: 1
	ChatID *string `json:"chatId"`

	// id instance
	// Required: true
	// Min Length: 1
	IDInstance *string `json:"idInstance"`

	// link preview
	LinkPreview bool `json:"linkPreview,omitempty"`

	// message
	// Required: true
	// Max Length: 20000
	// Min Length: 1
	Message *string `json:"message"`

	// quoted message Id
	QuotedMessageID string `json:"quotedMessageId,omitempty"`
}

// Validate validates this green API send message request
func (m *GreenAPISendMessageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPITokenInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChatID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GreenAPISendMessageRequest) validateAPITokenInstance(formats strfmt.Registry) error {

	if err := validate.Required("apiTokenInstance", "body", m.APITokenInstance); err != nil {
		return err
	}

	if err := validate.MinLength("apiTokenInstance", "body", *m.APITokenInstance, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendMessageRequest) validateChatID(formats strfmt.Registry) error {

	if err := validate.Required("chatId", "body", m.ChatID); err != nil {
		return err
	}

	if err := validate.MinLength("chatId", "body", *m.ChatID, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendMessageRequest) validateIDInstance(formats strfmt.Registry) error {

	if err := validate.Required("idInstance", "body", m.IDInstance); err != nil {
		return err
	}

	if err := validate.MinLength("idInstance", "body", *m.IDInstance, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPISendMessageRequest) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	if err := validate.MinLength("message", "body", *m.Message, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("message", "body", *m.Message, 20000); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this green API send message request based on context it is used
func (m *GreenAPISendMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GreenAPISendMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GreenAPISendMessageRequest) UnmarshalBinary(b []byte) error {
	var res GreenAPISendMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
