// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GreenAPIStateResponse green API state response
//
// swagger:model GreenAPIStateResponse
type GreenAPIStateResponse struct {

	// state instance
	// Enum: [notAuthorized authorized blocked sleepMode starting yellowCard]
	StateInstance string `json:"stateInstance,omitempty"`
}

// Validate validates this green API state response
func (m *GreenAPIStateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStateInstance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var greenApiStateResponseTypeStateInstancePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["notAuthorized","authorized","blocked","sleepMode","starting","yellowCard"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiStateResponseTypeStateInstancePropEnum = append(greenApiStateResponseTypeStateInstancePropEnum, v)
	}
}

const (

	// GreenAPIStateResponseStateInstanceNotAuthorized captures enum value "notAuthorized"
	GreenAPIStateResponseStateInstanceNotAuthorized string = "notAuthorized"

	// GreenAPIStateResponseStateInstanceAuthorized captures enum value "authorized"
	GreenAPIStateResponseStateInstanceAuthorized string = "authorized"

	// GreenAPIStateResponseStateInstanceBlocked captures enum value "blocked"
	GreenAPIStateResponseStateInstanceBlocked string = "blocked"

	// GreenAPIStateResponseStateInstanceSleepMode captures enum value "sleepMode"
	GreenAPIStateResponseStateInstanceSleepMode string = "sleepMode"

	// GreenAPIStateResponseStateInstanceStarting captures enum value "starting"
	GreenAPIStateResponseStateInstanceStarting string = "starting"

	// GreenAPIStateResponseStateInstanceYellowCard captures enum value "yellowCard"
	GreenAPIStateResponseStateInstanceYellowCard string = "yellowCard"
)

// prop value enum
func (m *GreenAPIStateResponse) validateStateInstanceEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiStateResponseTypeStateInstancePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPIStateResponse) validateStateInstance(formats strfmt.Registry) error {
	if swag.IsZero(m.StateInstance) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateInstanceEnum("stateInstance", "body", m.StateInstance); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this green API state response based on context it is used
func (m *GreenAPIStateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GreenAPIStateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GreenAPIStateResponse) UnmarshalBinary(b []byte) error {
	var res GreenAPIStateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
