// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GreenAPIGetRequest green API get request
//
// swagger:model GreenAPIGetRequest
type GreenAPIGetRequest struct {

	// api token instance
	// Required: true
	// Min Length: 1
	APITokenInstance *string `json:"apiTokenInstance"`

	// id instance
	// Required: true
	// Min Length: 1
	IDInstance *string `json:"idInstance"`
}

// Validate validates this green API get request
func (m *GreenAPIGetRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPITokenInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDInstance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GreenAPIGetRequest) validateAPITokenInstance(formats strfmt.Registry) error {

	if err := validate.Required("apiTokenInstance", "body", m.APITokenInstance); err != nil {
		return err
	}

	if err := validate.MinLength("apiTokenInstance", "body", *m.APITokenInstance, 1); err != nil {
		return err
	}

	return nil
}

func (m *GreenAPIGetRequest) validateIDInstance(formats strfmt.Registry) error {

	if err := validate.Required("idInstance", "body", m.IDInstance); err != nil {
		return err
	}

	if err := validate.MinLength("idInstance", "body", *m.IDInstance, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this green API get request based on context it is used
func (m *GreenAPIGetRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GreenAPIGetRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GreenAPIGetRequest) UnmarshalBinary(b []byte) error {
	var res GreenAPIGetRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
