// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GreenAPISettingsResponse green API settings response
//
// swagger:model GreenAPISettingsResponse
type GreenAPISettingsResponse struct {

	// auto typing
	AutoTyping int32 `json:"autoTyping,omitempty"`

	// delay send messages milliseconds
	DelaySendMessagesMilliseconds int32 `json:"delaySendMessagesMilliseconds,omitempty"`

	// deleted message webhook
	// Enum: [yes no]
	DeletedMessageWebhook string `json:"deletedMessageWebhook,omitempty"`

	// device webhook
	// Enum: [yes no]
	DeviceWebhook string `json:"deviceWebhook,omitempty"`

	// edited message webhook
	// Enum: [yes no]
	EditedMessageWebhook string `json:"editedMessageWebhook,omitempty"`

	// enable messages history
	// Enum: [yes no]
	EnableMessagesHistory string `json:"enableMessagesHistory,omitempty"`

	// incoming block webhook
	// Enum: [yes no]
	IncomingBlockWebhook string `json:"incomingBlockWebhook,omitempty"`

	// incoming call webhook
	// Enum: [yes no]
	IncomingCallWebhook string `json:"incomingCallWebhook,omitempty"`

	// incoming webhook
	// Enum: [yes no]
	IncomingWebhook string `json:"incomingWebhook,omitempty"`

	// keep online status
	// Enum: [yes no]
	KeepOnlineStatus string `json:"keepOnlineStatus,omitempty"`

	// link preview
	LinkPreview bool `json:"linkPreview,omitempty"`

	// mark incoming messages readed
	// Enum: [yes no]
	MarkIncomingMessagesReaded string `json:"markIncomingMessagesReaded,omitempty"`

	// mark incoming messages readed on reply
	// Enum: [yes no]
	MarkIncomingMessagesReadedOnReply string `json:"markIncomingMessagesReadedOnReply,omitempty"`

	// outgoing API message webhook
	// Enum: [yes no]
	OutgoingAPIMessageWebhook string `json:"outgoingAPIMessageWebhook,omitempty"`

	// outgoing message webhook
	// Enum: [yes no]
	OutgoingMessageWebhook string `json:"outgoingMessageWebhook,omitempty"`

	// outgoing webhook
	// Enum: [yes no]
	OutgoingWebhook string `json:"outgoingWebhook,omitempty"`

	// poll message webhook
	// Enum: [yes no]
	PollMessageWebhook string `json:"pollMessageWebhook,omitempty"`

	// shared session
	// Enum: [yes no]
	SharedSession string `json:"sharedSession,omitempty"`

	// state webhook
	// Enum: [yes no]
	StateWebhook string `json:"stateWebhook,omitempty"`

	// status instance webhook
	// Enum: [yes no]
	StatusInstanceWebhook string `json:"statusInstanceWebhook,omitempty"`

	// webhook Url
	WebhookURL string `json:"webhookUrl,omitempty"`

	// webhook Url token
	WebhookURLToken string `json:"webhookUrlToken,omitempty"`

	// wid
	Wid string `json:"wid,omitempty"`
}

// Validate validates this green API settings response
func (m *GreenAPISettingsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeletedMessageWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeviceWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEditedMessageWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnableMessagesHistory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIncomingBlockWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIncomingCallWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIncomingWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeepOnlineStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMarkIncomingMessagesReaded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMarkIncomingMessagesReadedOnReply(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutgoingAPIMessageWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutgoingMessageWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutgoingWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePollMessageWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSharedSession(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStateWebhook(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatusInstanceWebhook(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var greenApiSettingsResponseTypeDeletedMessageWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeDeletedMessageWebhookPropEnum = append(greenApiSettingsResponseTypeDeletedMessageWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseDeletedMessageWebhookYes captures enum value "yes"
	GreenAPISettingsResponseDeletedMessageWebhookYes string = "yes"

	// GreenAPISettingsResponseDeletedMessageWebhookNo captures enum value "no"
	GreenAPISettingsResponseDeletedMessageWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateDeletedMessageWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeDeletedMessageWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateDeletedMessageWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.DeletedMessageWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateDeletedMessageWebhookEnum("deletedMessageWebhook", "body", m.DeletedMessageWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeDeviceWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeDeviceWebhookPropEnum = append(greenApiSettingsResponseTypeDeviceWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseDeviceWebhookYes captures enum value "yes"
	GreenAPISettingsResponseDeviceWebhookYes string = "yes"

	// GreenAPISettingsResponseDeviceWebhookNo captures enum value "no"
	GreenAPISettingsResponseDeviceWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateDeviceWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeDeviceWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateDeviceWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.DeviceWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateDeviceWebhookEnum("deviceWebhook", "body", m.DeviceWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeEditedMessageWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeEditedMessageWebhookPropEnum = append(greenApiSettingsResponseTypeEditedMessageWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseEditedMessageWebhookYes captures enum value "yes"
	GreenAPISettingsResponseEditedMessageWebhookYes string = "yes"

	// GreenAPISettingsResponseEditedMessageWebhookNo captures enum value "no"
	GreenAPISettingsResponseEditedMessageWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateEditedMessageWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeEditedMessageWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateEditedMessageWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.EditedMessageWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateEditedMessageWebhookEnum("editedMessageWebhook", "body", m.EditedMessageWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeEnableMessagesHistoryPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeEnableMessagesHistoryPropEnum = append(greenApiSettingsResponseTypeEnableMessagesHistoryPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseEnableMessagesHistoryYes captures enum value "yes"
	GreenAPISettingsResponseEnableMessagesHistoryYes string = "yes"

	// GreenAPISettingsResponseEnableMessagesHistoryNo captures enum value "no"
	GreenAPISettingsResponseEnableMessagesHistoryNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateEnableMessagesHistoryEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeEnableMessagesHistoryPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateEnableMessagesHistory(formats strfmt.Registry) error {
	if swag.IsZero(m.EnableMessagesHistory) { // not required
		return nil
	}

	// value enum
	if err := m.validateEnableMessagesHistoryEnum("enableMessagesHistory", "body", m.EnableMessagesHistory); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeIncomingBlockWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeIncomingBlockWebhookPropEnum = append(greenApiSettingsResponseTypeIncomingBlockWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseIncomingBlockWebhookYes captures enum value "yes"
	GreenAPISettingsResponseIncomingBlockWebhookYes string = "yes"

	// GreenAPISettingsResponseIncomingBlockWebhookNo captures enum value "no"
	GreenAPISettingsResponseIncomingBlockWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateIncomingBlockWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeIncomingBlockWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateIncomingBlockWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.IncomingBlockWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateIncomingBlockWebhookEnum("incomingBlockWebhook", "body", m.IncomingBlockWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeIncomingCallWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeIncomingCallWebhookPropEnum = append(greenApiSettingsResponseTypeIncomingCallWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseIncomingCallWebhookYes captures enum value "yes"
	GreenAPISettingsResponseIncomingCallWebhookYes string = "yes"

	// GreenAPISettingsResponseIncomingCallWebhookNo captures enum value "no"
	GreenAPISettingsResponseIncomingCallWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateIncomingCallWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeIncomingCallWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateIncomingCallWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.IncomingCallWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateIncomingCallWebhookEnum("incomingCallWebhook", "body", m.IncomingCallWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeIncomingWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeIncomingWebhookPropEnum = append(greenApiSettingsResponseTypeIncomingWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseIncomingWebhookYes captures enum value "yes"
	GreenAPISettingsResponseIncomingWebhookYes string = "yes"

	// GreenAPISettingsResponseIncomingWebhookNo captures enum value "no"
	GreenAPISettingsResponseIncomingWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateIncomingWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeIncomingWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateIncomingWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.IncomingWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateIncomingWebhookEnum("incomingWebhook", "body", m.IncomingWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeKeepOnlineStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeKeepOnlineStatusPropEnum = append(greenApiSettingsResponseTypeKeepOnlineStatusPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseKeepOnlineStatusYes captures enum value "yes"
	GreenAPISettingsResponseKeepOnlineStatusYes string = "yes"

	// GreenAPISettingsResponseKeepOnlineStatusNo captures enum value "no"
	GreenAPISettingsResponseKeepOnlineStatusNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateKeepOnlineStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeKeepOnlineStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateKeepOnlineStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.KeepOnlineStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateKeepOnlineStatusEnum("keepOnlineStatus", "body", m.KeepOnlineStatus); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeMarkIncomingMessagesReadedPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeMarkIncomingMessagesReadedPropEnum = append(greenApiSettingsResponseTypeMarkIncomingMessagesReadedPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseMarkIncomingMessagesReadedYes captures enum value "yes"
	GreenAPISettingsResponseMarkIncomingMessagesReadedYes string = "yes"

	// GreenAPISettingsResponseMarkIncomingMessagesReadedNo captures enum value "no"
	GreenAPISettingsResponseMarkIncomingMessagesReadedNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateMarkIncomingMessagesReadedEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeMarkIncomingMessagesReadedPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateMarkIncomingMessagesReaded(formats strfmt.Registry) error {
	if swag.IsZero(m.MarkIncomingMessagesReaded) { // not required
		return nil
	}

	// value enum
	if err := m.validateMarkIncomingMessagesReadedEnum("markIncomingMessagesReaded", "body", m.MarkIncomingMessagesReaded); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeMarkIncomingMessagesReadedOnReplyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeMarkIncomingMessagesReadedOnReplyPropEnum = append(greenApiSettingsResponseTypeMarkIncomingMessagesReadedOnReplyPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseMarkIncomingMessagesReadedOnReplyYes captures enum value "yes"
	GreenAPISettingsResponseMarkIncomingMessagesReadedOnReplyYes string = "yes"

	// GreenAPISettingsResponseMarkIncomingMessagesReadedOnReplyNo captures enum value "no"
	GreenAPISettingsResponseMarkIncomingMessagesReadedOnReplyNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateMarkIncomingMessagesReadedOnReplyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeMarkIncomingMessagesReadedOnReplyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateMarkIncomingMessagesReadedOnReply(formats strfmt.Registry) error {
	if swag.IsZero(m.MarkIncomingMessagesReadedOnReply) { // not required
		return nil
	}

	// value enum
	if err := m.validateMarkIncomingMessagesReadedOnReplyEnum("markIncomingMessagesReadedOnReply", "body", m.MarkIncomingMessagesReadedOnReply); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeOutgoingAPIMessageWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeOutgoingAPIMessageWebhookPropEnum = append(greenApiSettingsResponseTypeOutgoingAPIMessageWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseOutgoingAPIMessageWebhookYes captures enum value "yes"
	GreenAPISettingsResponseOutgoingAPIMessageWebhookYes string = "yes"

	// GreenAPISettingsResponseOutgoingAPIMessageWebhookNo captures enum value "no"
	GreenAPISettingsResponseOutgoingAPIMessageWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateOutgoingAPIMessageWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeOutgoingAPIMessageWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateOutgoingAPIMessageWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.OutgoingAPIMessageWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateOutgoingAPIMessageWebhookEnum("outgoingAPIMessageWebhook", "body", m.OutgoingAPIMessageWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeOutgoingMessageWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeOutgoingMessageWebhookPropEnum = append(greenApiSettingsResponseTypeOutgoingMessageWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseOutgoingMessageWebhookYes captures enum value "yes"
	GreenAPISettingsResponseOutgoingMessageWebhookYes string = "yes"

	// GreenAPISettingsResponseOutgoingMessageWebhookNo captures enum value "no"
	GreenAPISettingsResponseOutgoingMessageWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateOutgoingMessageWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeOutgoingMessageWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateOutgoingMessageWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.OutgoingMessageWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateOutgoingMessageWebhookEnum("outgoingMessageWebhook", "body", m.OutgoingMessageWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeOutgoingWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeOutgoingWebhookPropEnum = append(greenApiSettingsResponseTypeOutgoingWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseOutgoingWebhookYes captures enum value "yes"
	GreenAPISettingsResponseOutgoingWebhookYes string = "yes"

	// GreenAPISettingsResponseOutgoingWebhookNo captures enum value "no"
	GreenAPISettingsResponseOutgoingWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateOutgoingWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeOutgoingWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateOutgoingWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.OutgoingWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateOutgoingWebhookEnum("outgoingWebhook", "body", m.OutgoingWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypePollMessageWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypePollMessageWebhookPropEnum = append(greenApiSettingsResponseTypePollMessageWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponsePollMessageWebhookYes captures enum value "yes"
	GreenAPISettingsResponsePollMessageWebhookYes string = "yes"

	// GreenAPISettingsResponsePollMessageWebhookNo captures enum value "no"
	GreenAPISettingsResponsePollMessageWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validatePollMessageWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypePollMessageWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validatePollMessageWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.PollMessageWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validatePollMessageWebhookEnum("pollMessageWebhook", "body", m.PollMessageWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeSharedSessionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeSharedSessionPropEnum = append(greenApiSettingsResponseTypeSharedSessionPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseSharedSessionYes captures enum value "yes"
	GreenAPISettingsResponseSharedSessionYes string = "yes"

	// GreenAPISettingsResponseSharedSessionNo captures enum value "no"
	GreenAPISettingsResponseSharedSessionNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateSharedSessionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeSharedSessionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateSharedSession(formats strfmt.Registry) error {
	if swag.IsZero(m.SharedSession) { // not required
		return nil
	}

	// value enum
	if err := m.validateSharedSessionEnum("sharedSession", "body", m.SharedSession); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeStateWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeStateWebhookPropEnum = append(greenApiSettingsResponseTypeStateWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseStateWebhookYes captures enum value "yes"
	GreenAPISettingsResponseStateWebhookYes string = "yes"

	// GreenAPISettingsResponseStateWebhookNo captures enum value "no"
	GreenAPISettingsResponseStateWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateStateWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeStateWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateStateWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.StateWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateWebhookEnum("stateWebhook", "body", m.StateWebhook); err != nil {
		return err
	}

	return nil
}

var greenApiSettingsResponseTypeStatusInstanceWebhookPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["yes","no"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		greenApiSettingsResponseTypeStatusInstanceWebhookPropEnum = append(greenApiSettingsResponseTypeStatusInstanceWebhookPropEnum, v)
	}
}

const (

	// GreenAPISettingsResponseStatusInstanceWebhookYes captures enum value "yes"
	GreenAPISettingsResponseStatusInstanceWebhookYes string = "yes"

	// GreenAPISettingsResponseStatusInstanceWebhookNo captures enum value "no"
	GreenAPISettingsResponseStatusInstanceWebhookNo string = "no"
)

// prop value enum
func (m *GreenAPISettingsResponse) validateStatusInstanceWebhookEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, greenApiSettingsResponseTypeStatusInstanceWebhookPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GreenAPISettingsResponse) validateStatusInstanceWebhook(formats strfmt.Registry) error {
	if swag.IsZero(m.StatusInstanceWebhook) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusInstanceWebhookEnum("statusInstanceWebhook", "body", m.StatusInstanceWebhook); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this green API settings response based on context it is used
func (m *GreenAPISettingsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GreenAPISettingsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GreenAPISettingsResponse) UnmarshalBinary(b []byte) error {
	var res GreenAPISettingsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
